name: Deploy to Test Server

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to test server
      run: |
        ssh admon@172.18.0.30 "
          cd /var/www/Intranet &&
          git pull origin test &&
          composer install --no-interaction --prefer-dist --optimize-autoloader &&
          npm install &&
          npm run build &&
          php artisan config:clear &&
          php artisan route:clear &&
          php artisan view:clear &&
          php artisan cache:clear
        "